name: codenoah
description: A new codenoah package project.
version: 0.0.2
homepage: https://github.com/NuhcanATAR/codenoah

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # database
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2
  firebase_messaging: ^15.1.4

  # util
  another_flushbar: ^1.12.30
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  very_good_analysis: ^5.1.0

flutter:

 
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Popins Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
